### ISSUE TITLE
rekey results in invalid database

### ISSUE THREAD

**Issue by rogerbinns** [utelle/SQLite3MultipleCiphers#165]
````
import apsw

con = apsw.Connection("testdb")
con.pragma("cipher", "rc4")
con.pragma("key", "hello")
con.execute("create table x(y); insert into x values(randomblob(656536))")

con.pragma("cipher", "ascon128")
con.pragma("rekey", "world")
con.execute("insert into x values(randomblob(656536))")
````

When the final execute happens  I get `SQLError: attached databases must use the same text encoding as main database` which it not right.

**Comment by utelle** [comment]
Typically, `PRAGMA rekey` should be used to change the passphrase only, not the cipher scheme.

The _rekey_ function uses a modified _vacuum_ procedure internally , if the cipher scheme should be changed at the same time. I have to analyze, what goes wrong for the various cipher combinations. It could well be that certain combinations don't work at all due to some SQLite restriction.

_SQLCipher_ for example doesn't support `PRAGMA rekey` at all for encrypting a plain database or for decrypting an encrypted database. Only changing the passphrase is supported.

Of course, I will further investigate this issue, but it will not have highest priority. Just changing the passphrase should always work, and for changing the cipher scheme there is the alternative of `vacuum into`.

**Comment by rogerbinns** [comment]
> SQLCipher for example doesn't support PRAGMA rekey at all for encrypting a plain database

I refer to the [docs](https://utelle.github.io/SQLite3MultipleCiphers/docs/configuration/config_sql_pragmas/#pragma-rekey--hexrekey):

> The PRAGMA rekey resp PRAGMA hexrekey statement has 3 use cases:
>
> 1. Encrypt an existing unencrypted database
> 2. Change the encryption key of an existing encrypted database
> 3. Remove encryption from an existing encrypted database

Unless an error is returned, it means the action is supported!  Things that are not supported must error, and I am fine with that.

For the record the vast majority of rekeying does work.

**Comment by rogerbinns** [comment]
I find the [regular page_size](https://www.sqlite.org/pragma.html#pragma_page_size) differing from [legacy_page_size](https://utelle.github.io/SQLite3MultipleCiphers/docs/configuration/config_sql_pragmas/#pragma-legacy_page_size) confusing.  If both are set, which takes priority?  Why does legacy_page_size even exist?

Also although the documentation says legacy_page_size **must** be a power of 2,. the pragma happily accepts *any* values from 1 through 65536 inclusive, like 5432;.

BTW my original assumption was the cryptography was using its own pages within the SQLite pages - ie a cryptography block size that could be independent of the SQLite page size, which in turn is independent of the filesystem block size.

**Comment by utelle** [comment]
> I find the [regular page_size](https://www.sqlite.org/pragma.html#pragma_page_size) differing from [legacy_page_size](https://utelle.github.io/SQLite3MultipleCiphers/docs/configuration/config_sql_pragmas/#pragma-legacy_page_size) confusing.

Yes, it is confusing, although I tried hard to explain it in the documentation.

The problem is that the SQLite database header contains information about the page size of the database file. This information is read by SQLite **before** the encryption extension has a chance to initialize the required cipher scheme. Therefore the official _SQLite Encryption Extension_ (SEE) leaves exactly 8 bytes of the database header **unencrypted**, so that the page size can determined, before initializing SEE. Typically a cipher scheme needs to know the page size to be able to locate the reserved bytes per page.

However, the original versions of _SQLCipher_, _sqleet_, and (very early) versions of _wxSQLite3_ encrypt the **complete** header. This prevents SQLite from determining the correct page size, so that typically the default page size (currently 4096) will be used. In most cases this works, because the database actually **has** the default page size, but for example prior versions of _SQLCipher_ used a page size of 1024.

> If both are set, which takes priority?

First, the legacy page size will be set, but it can be overwritten by a `pragma page_size`.

> Why does legacy_page_size even exist?

Different legacy cipher schemes use different page sizes. Specifying the default legacy page size spares the user from explicitly issuing a `pragma page_size`. If the database does not use the default, using `pragma page_size` will be still required, unless the legacy page size was adjusted accordingly.

> Also although the documentation says legacy_page_size **must** be a power of 2,. the pragma happily accepts _any_ values from 1 through 65536 inclusive, like 5432;.

You are right. This should be corrected. SQLite's `pragma page_size` does not issue an error message, if a wrong page size was specified, but it will not change the value in that case.

> BTW my original assumption was the cryptography was using its own pages within the SQLite pages - ie a cryptography block size that could be independent of the SQLite page size, which in turn is independent of the filesystem block size.

No, the actual page size must be a power of 2. Cipher schemes (or VFSes, to be more generic) are allowed to reserve up to 255 bytes per page for their own use (for example, for nonce, HMACs or other data). SQLite will then use `page size - reserved bytes` bytes of a page for storing database content.

**Comment by utelle** [comment]
> You've explained why the page size needs to be known before first access in many cipher configurations.

Only for **legacy** cipher schemes. Otherwise SQLite **knows** the page size from the database header.

> But not why **legacy_page_size** exists.

It is required for setting the page size of a database which is encrypted with a legacy cipher scheme.

> I don't see how having it spares you from a **page_size** pragma

Sorry, my explanation was unfortunately not correct regarding `pragma page_size`. `pragma page_size` can be used to set page size for a **new** database or to **change** the page size of an existing database. For databases encrypted with legacy cipher schemes setting the page size for an existing database is required. And that can be done with `pragma legacy_page_size` only.

The parameter `legacy_page_size` has a default value for each **legacy** cipher scheme. For example 1024 for SQLCipher up to version 3. Usually you don't have to explicitly set `legacy_page_size`, but maybe a project decided to use a different page size, say 16384. Then pragma `legacy_page_size` allows to change the default legacy page size.

> if you need to set the page size in advance, why are there two different pragmas that have the same effect?

`pragma page_size` is handled by SQLite, `pragma legacy_page_size` is handled by SQLite3MC. And their effect is **not** the same. The main purpose of `pragma page_size` is to **change** the page size of a database (or to query the page size). `pragma legacy_page_size` **sets** the page size of an existing legacy database, so that SQLite then knows the correct page size.

Pragma statements can currently only be used to change the configuration of the currently selected cipher. However, the default configuration of any supported cipher scheme can be adjusted via SQL functions. This can be useful, if an application has to deal with many databases which are **attached** to a database connection.

**Comment by utelle** [comment]
> Also although the documentation says legacy_page_size must be a power of 2,. the pragma happily accepts any values from 1 through 65536 inclusive, like 5432;.

This has been fixed in commit 56ac1e2f7a703efe2924ea0fa0691bbe03bb03f4. Now only valid page sizes are accepted. Otherwise the value is not changed.

**Comment by utelle** [comment]
Commit efdb69421800cdac6a7c6bfe9759f62287b2b5e6 should fix the issue.

If there are still cases for which rekeying results in corrupted databases, please reopen.

**Comment by rogerbinns** [comment]
Running `python3 -m apsw.mcall` I no longer see corrupt databases.  I do still see #164 where rekey pragma returns `SQLITE_ERROR` and does not set the error string.

**Comment by rogerbinns** [comment]
Found another corrupt database, which also causes an assertion failure in debug build
````
import apsw

con = apsw.Connection("testdb")
con.execute("create table x(y); insert into x values(randomblob(65536))")
con.pragma("cipher", "sqlcipher")
con.pragma("plaintext_header_size", 33)
con.pragma("fast_kdf_iter", 63)
con.pragma("hmac_algorithm", 1)
con.pragma("hexrekey", "aabbccdd")
con.execute("insert into x select * from x")
````

Note that `plaintext_header_size` is documented as being a multiple of 32 but any value is accepted.  Setting it to 32 makes no difference in this failure.

**Comment by utelle** [comment]
> Found another corrupt database, which also causes an assertion failure in debug build
> 
> ```
> import apsw
> 
> con = apsw.Connection("testdb")
> con.execute("create table x(y); insert into x values(randomblob(65536))")
> con.pragma("cipher", "sqlcipher")
> con.pragma("plaintext_header_size", 33)
> con.pragma("fast_kdf_iter", 63)
> con.pragma("hmac_algorithm", 1)
> con.pragma("hexrekey", "aabbccdd")
> con.execute("insert into x select * from x")
> ```
> 
> Note that `plaintext_header_size` is documented as being a multiple of 32 but any value is accepted. Setting it to 32 makes no difference in this failure.

Yes, just as for `legacy_page_size` it will be necessary to check that the values for `plaintext_header_size` take valid values only. _SQLite3 Multiple Ciphers_ will happily accept any value, because the underlying AES algorithm uses _Cypher Text Stealing_ if the buffer length is not a multiple of 16. However, the resulting database will no longer be compatible with the original SQLCipher implementation.

Thanks for the sample. This will help to analyze what is going wrong and where.

For the situation where the `SQL logic error` is thrown I have found out that the rekey operation fails with an error code (but without a message from rekey). The text `SQL logic error` is the default text for error code `SQLITE_ERROR`.

I'm quite confident that I will manage to resolve this issue within the next couple of days.

Thanks for the hint how to use gdb to catch assertions.

**Comment by utelle** [comment]
I finally found the cause for the pager assertion. The HMAC size for HMAC algorithm SHA256 of SQLCipher was reported incorrectly. Thus, the HMAC was written partially outside of the page buffer bounds.

Commit 02b69ad7418a59530253d1ed5061a94b0016ca49 fixes this. At least in my development environment, the test sample `mcall.py` does no longer throw exceptions.
